docs/conf.py
docs/project_info/contributing.rst
haptools/__main__.py
haptools/haputils/haplotypes.py
haptools/karyogram/karyogram.py
haptools/simgenotype/sim_admixture.py
haptools/simphenotype/sim_phenotypes.py
poetry.lock
pyproject.toml

resolves #22 and ensures that our poetry.lock file is stable and contains all of the dependencies it needs
after merging, everyone should rerun
```
poetry install -E docs -E test
```
I also removed `pytabix` from the dependency list in favor of `pysam` to address [this comment](https://github.com/gymrek-lab/haptools/commit/18786ebf65fb2110893ec47d0242bf8159334968#r70766203)

fix: dependencies

---

docs/commands/transform.rst
docs/index.rst
haptools/__main__.py
haptools/data/__init__.py
haptools/data/data.py
haptools/data/genotypes.py
haptools/data/haplotypes.py
haptools/haplotype.py
haptools/sim_admixture.py
tests/test_data.py

resolves #33 
**note**: please merge this before #43 !
This PR adds a subcommand to output haplotypes in VCF format, so that we can obtain counts of each haplotype in each chromosome of each sample. This functionality is primarily handled by a new `Haplotype.transform()` method.
There is also a `Haplotypes.transform()` method to transform multiple haplotypes at once. At the moment, `Haplotypes.transform()` just calls `Haplotype.transform()` repeatedly, but I think there might be ways to make this faster.
There are also new methods to write the haplotypes to a VCF and some small improvements to make reading from VCFs less memory-intensive.
I've documented the `transform` subcommand [here](https://haptools--45.org.readthedocs.build/en/45/commands/transform.html) in the _commands_ section. …

feat: `transform` subcommand

---

docs/commands/simphenotype.rst
docs/commands/transform.rst
haptools/__main__.py
haptools/sim_phenotype.py

This fixes an issue in `simphenotype` where the `-h` parameter meant two different things.

fix: conflicting short params in simphenotype

---

docs/api/data.rst
docs/api/examples.rst
docs/commands/ld.rst
docs/commands/transform.rst
docs/formats/haplotypes.rst
docs/index.rst

resolves #118
This PR fixes some errors in the snp2hap example within the API docs. In addition, it adds a description of the ancestry extra field to a separate section of the Haplotypes documentation.
It also describes how to use the Logger module in the API docs and explains how to query from a tabix-indexed hap file.

docs: update snp2hap example

---

docs/api/data.rst
docs/api/examples.rst
docs/conf.py
haptools/__main__.py
haptools/admix_storage.py
haptools/data/breakpoints.py
haptools/data/genotypes.py
haptools/data/haplotypes.py
haptools/index.py
haptools/ld.py
haptools/sim_genotype.py
haptools/transform.py
pyproject.toml
tests/test_data.py
tests/test_karyogram.py
tests/test_outputvcf.py

See #19 
----
This PR removes the `to_MAC()` method and the AAF field from the `variants` property of the Genotypes class. Both are **breaking changes** to the Genotypes API.
Instead, we introduce a new `check_maf()` method, which offers a cleaner, more streamlined interface.
```
genotypes = data.Genotypes.load('tests/data/simple.vcf.gz')
genotypes.check_maf(threshold=0.05)
```
----
This PR also uses `black` to reformat many of the files in our codebase to follow Python's PEP8 style standards. If I thought a file would require too many changes to bring it up to date with the standards, I just excluded it from formatting by listing it in the `extend-exclude` section of our `pyproject.toml` file.
Once this PR is merged, we'll be able to check the formatting of all of the code in our …

feat: `Genotypes.check_maf()` method

---

README.md
docs/api/data.rst
docs/commands/karyogram.rst
docs/commands/simphenotype.rst
docs/commands/transform.rst
docs/formats/genotypes.rst
docs/formats/haplotypes.rst
docs/index.rst
docs/project_info/installation.rst
haptools/data/breakpoints.py
haptools/data/genotypes.py
haptools/data/haplotypes.py
haptools/transform.py
poetry.lock
pyproject.toml
tests/test_data.py
tests/test_transform.py

resolves #125
This PR also creates a `Haplotypes.subset()` method (see https://github.com/CAST-genomics/haptools/issues/19#issuecomment-1126651795) to automatically subset the set of haplotypes if their variants aren't all present in the genotypes file.

docs: cleanup and improve descriptions

---

pyproject.toml

agh! our installation is broken!
pysam doesn't have support for 3.11 yet, and we depend on pysam
so if the user tries to install haptools with python 3.11, pip will install pysam from its sdist instead of its wheel
...and sdists always cause problems

dep: require <3.11 to resolve pysam install error

---

.readthedocs.yaml
docs/conf.py
docs/formats/models.rst
haptools/__init__.py
haptools/__main__.py
haptools/data/breakpoints.py
haptools/data/genotypes.py
haptools/logging.py
poetry.lock
pyproject.toml
tests/test_data.py

all of our docs are in rst now, so we can remove myst-parser as a dependency
this PR also sets up automatic versioning of our project. In future releases, we only need to update the version listed in our `pyproject.toml` to bump our version

dep: remove myst-parser

---

.gitignore
docs/conf.py
docs/project_info/contributing.rst
docs/project_info/installation.rst
haptools/data/breakpoints.py
haptools/data/covariates.py
haptools/data/data.py
haptools/data/genotypes.py
haptools/data/haplotypes.py
haptools/data/phenotypes.py
haptools/index.py
haptools/ld.py
noxfile.py
poetry.lock
pyproject.toml
tests/test_index.py

This PR installs and configures `nox`. All in all, `nox` can handle three different types of checks now:
1. Checking that the docs can be built without errors
2. Linting and style checking
3. Running our test suite across python versions 3.7-3.10
--------
In the process of doing this, I discovered a **bug** with `haptools` in python 3.10+ : _reading and writing compressed text files results in an error_! There was a change in the behavior of python's `fileinput.hook_compressed()` that resulted in errors when it reads/writes compressed files. Unfortunately, `haptools` uses this function extensively, so this change affects the python API and nearly all command line utilities. This PR fixes the bug for the next release of `haptools`.

fix: file reads and writes in py3.10+

---

.github/workflows/conventional-prs.yml
.github/workflows/tests.yml
docs/project_info/contributing.rst
docs/project_info/installation.rst
haptools/sim_genotype.py
haptools/sim_phenotype.py
tests/test_simphenotype.py

resolves [#95](https://github.com/CAST-genomics/haptools/issues/95#issuecomment-1310723656)
If the genotypes are all the same, they will have a variance of 0, so the noise term ends up being 0. However, if the user specified a heritability value, then there should be some reasonable expectation of noise in the output.
This PR also adds a test to cover this edge case.

fix: case where genotypes are all the same but heritability is specified in `simphenotype`

---

docs/api/data.rst
haptools/data/phenotypes.py
tests/test_data.py
tests/test_simphenotype.py

Changes the type of the samples parameter in the `data.Phenotypes.read` and `data.Phenotypes.__iter__` methods to a set
This is just a bit more efficient. Instead of converting the argument to a set internally, we just rely upon it being a set to begin with.

refactor: `data.Phenotypes` samples parameter to be of type set

---

tests/test_data.py

This PR adds tests for a hidden feature in the `GenotypesPLINK` class: the `_prephased` property. It can save memory and time when you already know that your genotypes are phased: we won't have to load and check the phase information when reading your genotypes.
I'll take this opportunity to stress that this function should not be used in any real scripts or code! It's just for internal (and theoretical) use. In fact, I'm creating this PR because I think the code doesn't work properly, and I'm trying to reproduce some issues I was having with it.

test: hidden phasing property in `GenotypesPLINK` class

---

docs/project_info/contributing.rst
haptools/__main__.py
haptools/index.py
haptools/ld.py
haptools/logging.py
haptools/sim_phenotype.py
haptools/transform.py

After reading [this article](https://coralogix.com/blog/python-logging-best-practices-tips/), I realized that I wasn't creating my logger objects properly. The way that I was doing it would affect the root logger object and, subsequently, any loggers in other python libraries that inherit from the root logger.
This PR creates a new custom logging module within haptools. We reduce boilerplate by just using the custom logging module to get our logger objects from now on. I also documented all of this in our contributing docs.

fix: logging so that it doesn't affect the root logger

---

haptools/__main__.py
haptools/sim_phenotype.py
tests/test_simphenotype.py

resolves #147 by adding a parameter that can disable genotype normalization

feat: a new `--no-normalize` parameter for `simphenotype`

---

docs/commands/simgenotype.rst
docs/formats/models.rst
haptools/__main__.py

Updated the simgenotype docs page, models doc page, and the click documentation to better lead people where they can find example files for the input formats for simgenotype.

docs: better showcase example files and their locations in `simgenotype`

---

docs/commands/index.rst
docs/commands/karyogram.rst
docs/commands/ld.rst
docs/commands/simgenotype.rst
docs/commands/simphenotype.rst
docs/commands/transform.rst
docs/formats/haplotypes.rst
docs/index.rst
docs/project_info/contributing.rst
docs/project_info/example_files.rst
haptools/__main__.py

This PR resolves #169 
The main changes are
1. A new "Motivation" section on the page for the Haplotype file format that motivates the need for a new format and discusses its advantages over the alternatives
2. A new page titled "Example files" that describes where the example and test files are located as well as how to execute our tests using the example files. We've linked to this page at the bottom of each command's documentation page.
3. A new "Logging" section on the front page of our documentation that describes how to get log info from `haptools`

docs: updates for v0.1.0

---

.github/workflows/constraints.txt
tests/test_data.py

Closes #173 
Second attempt at resolving the build issue from https://github.com/CAST-genomics/haptools/commit/6eac7ef2e8bc81f1cdedc98b446c03c2641b52cf. This time, we're taking a less destructive approach by only upgrading poetry in the build pipeline instead of bumping it completely. The benefit of this is that we'll be able to keep python 3.7 support for a little longer instead of doing #173

build: bump the version of poetry used in our CD pipeline

---

pyproject.toml

To fix the broken build in https://github.com/CAST-genomics/haptools/commit/541828b88473d0618d757a4d30ea96000e436e21, we need to declare a README in our pyproject.toml

fix: add poetry readme to fix long_description when publishing to pypi

---

tests/test_index.py

unfortunately, different versions of pysam will generate different tbi files, so we can't just check whether the tbi files that are generated are the same as those that we have already
so we can only safely test whether the tbi files exist

test: loosen requirements for tbi files output by the `index` command

---

docs/api/data.rst
docs/api/haptools.rst
haptools/data/haplotypes.py
haptools/data/phenotypes.py
tests/test_data.py

Fixes a bug in `Haplotypes.__iter__()` and some issues with some of the example docs for the `Haplotype` class in the API section.
This PR also adds a new method `test_iterate` to the `TestHaplotypes` class in our test suite. It includes comprehensive testing for all kinds of different edge-cases in `Hapltypes.__iter__()`

fix: NoneType error in `Haplotypes.__iter__`

---

haptools/data/phenotypes.py
tests/test_data.py

This fixes a serious issue with the way that haptools writes phenotypes to `.pheno` files. Up until now, it would sometimes drop the sign of any negative phenotype values and leave only two units of precision past the decimal point for floating points. This new code should make the phenotype values much more precise and fix the sign issue.
Users of `simphenotype` should rerun any analyses with this new code. Shoutout to @LiterallyUniqueLogin for finding this bug and helping me debug it! I've been banging my head for days.

fix: precision of phenotypes written to pheno file

---

haptools/sim_genotype.py
tests/test_outputvcf.py

Added logic in simgenotype on lines 386-387 and 872-873 to check if file ending in .map will even have chr{1-22,X} before grabbing the group to prevent the code from erroring out even though we have valid coordinate files in the directory.

fix: Added logic to finding all coord files

---

docs/api/data.rst
haptools/data/phenotypes.py
tests/test_data.py

...so that we can handle situations (within happler) where samples in a phenotypes file don't appear in the same order as those in the genotypes file
note: this idea first appeared in https://github.com/CAST-genomics/haptools/issues/19#issuecomment-1126651795

feat: new `Phenotypes.subset()` method

---

haptools/data/covariates.py
tests/test_data.py

we need to call `super()` on the parent class, not the grandparent class

fix: `Covariates.__init__` after updates to parent class

---

haptools/clump.py
haptools/data/genotypes.py
tests/test_clump.py

Since cyvcf2 can also return -2 we updated check_missing and clump to account for these changes. Also fixed logic error in filtering str values in clump.

fix: check missing to check for 254

---

docs/api/data.rst
haptools/clump.py
haptools/data/genotypes.py

When loading a GenotypeTR class you can now specify what the type of vcf you are currently reading.
Example
```
genotypes = data.GenotypesTR.load('tests/data/simple_tr.vcf', vcftype='hipstr')
```
you can choose between
```
vcftype : {'auto', 'gangstr', 'advntr', 'hipstr', 'eh', 'popstr'}
```

feat: Added ability to set vcftype for reading str files

---

docs/commands/ld.rst
haptools/ld.py
tests/test_ld.py

A future release of haptools will add support for repeats in the `ld` command. Unfortunately, that will very likely require us to make breaking changes to the `ld` command to make the interface flexible enough for users to be able to specify all of the possible ways to compute LD with a repeat or a set of repeats. So for now, we will just delay the breaking changes and explicitly ignore repeats in the meantime.
Users who are interested in computing LD with repeats may use the haptools API or PLINK2's `--ld dosage` feature until we add support.

fix: explicitly ignore repeats in the `ld` command

---

.readthedocs.yaml
haptools/data/genotypes.py
haptools/data/phenotypes.py
tests/test_data.py

and also fix a message in `Genotypes.check_maf()`
and also upgrade our readthedocs config to avoid deprecations

fix: bug where `Phenotypes.subset(inplace=True)` would raise an AttributeError

---

haptools/__init__.py
haptools/data/haplotypes.py
tests/test_data.py

Thanks to @XimeiWulilyy for reporting the issue and providing a detailed report and minimally reproducible example!

fix: `UnboundLocalError` arising from headerless `.hap` files

---

haptools/__main__.py
haptools/data/genotypes.py
haptools/ld.py
haptools/sim_phenotype.py
haptools/transform.py
tests/test_data.py

closes #228 and overrides it
The `Genotypes.read` and `Genotypes.__init__` methods expect samples to be provided as a list but make no guarantee that the samples will be loaded in the ordering requested. (This is because the underlying libraries that we use do not make this guarantee either.)
We first attempted to solve this issue in #225 by automatically reordering after reading the genotypes. But then we realized this would double the memory of the `read()` method.
PR #228 takes a different approach to the problem by adding a `reorder_samples` argument to the `Genotypes` classes that would do the reordering only if it is requested. This approach would also have required us to do more work to implement extra checks (see https://github.com/CAST-genomics/haptools/pull/228#issuecomment-18168 …

feat: convert `samples` arg in `Genotypes` classes into a set

---

.github/workflows/tests.yml
.readthedocs.yaml

see https://github.com/gymrek-lab/TRTools/pull/218, since TRTools uses the same github actions
Our pull request checks broke because of https://github.com/readthedocs/readthedocs.org/issues/11150 and https://github.com/actions/runner-images/issues/9741 ! Let's fix them

ci: fix broken github actions

---

dev-env.yml
poetry.lock
pyproject.toml

numpy 2.0 is coming out in 11 days! I hope the python world is ready

fix: disable numpy 2.0 since our dependencies don't yet work with it

---

.github/workflows/release.yml

see https://docs.pypi.org/trusted-publishers for more details
This is a more secure way of publishing to PyPI. I've configured [the new GitHub "environment" system](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment) to require reviews from someone in @CAST-genomics/haptools each time before a new release gets uploaded to PyPI

ci: use trusted publishing with pypi

---

.github/workflows/tests.yml

Does haptools run on M1 Apple silicon now that our dependencies have added support for it? (See https://github.com/bioconda/bioconda-recipes/pull/50219 and https://github.com/bioconda/bioconda-recipes/pull/50220)
Let's add a test to our CI for this. If it works, then we can add `osx-arm64` to the "additional platforms" that are supported in our bioconda recipe

feat: support for Apple M1 silicon

---

haptools/data/genotypes.py
tests/test_data.py
tests/test_simphenotype.py

Previous behavior was to error out with a cryptic ValueError and raise a warning. Now, we still raise the warning but we don't error out.

fix: load an empty array if there are no variants in `GenotypesVCF.read`

---

.devcontainer.json
.github/workflows/conventional-prs.yml
.github/workflows/tests.yml

Mambaforge is being deprecated https://github.com/conda-incubator/setup-miniconda/pull/360. Also old versions of nodejs in GitHub actions.
This PR cleans up all of the warnings in our CI. For an example, compare [before](https://github.com/CAST-genomics/haptools/actions/runs/11167234622) vs [after](https://github.com/CAST-genomics/haptools/actions/runs/11167563294).

ci: handle deprecations in gh actions and devcontainer

---

.devcontainer.json
docs/api/data.rst
haptools/data/haplotypes.py
tests/test_data.py

This allows users to safely merge Haplotypes objects
Update 10/14/24: I also added `len()` methods to the Haplotypes and Haplotype classes

feat: a new `Haplotypes.merge()` method

---

docs/api/data.rst
docs/formats/genotypes.rst
haptools/sim_phenotype.py
tests/test_simphenotype.py

If `--repeats` wasn't specified but the input hap file only contains R lines, `simphenotype` should automatically load the genotypes file with GenotypesTR or GenotypesPLINKTR. However, at the moment, it only uses GenotypesTR and not GenotypesPLINKTR
So this PR adds support for PGEN files, as well

fix: allow `simphenotype` to accept TR PGENs without `--repeats`

---

haptools/data/breakpoints.py
tests/test_data.py

...so that they can be made consistent across calls to `encode()` on different bp files
At the moment, `encode()` will choose integers to pair with each population label in the order that the labels appear in the bp file. So "AMR" will be assigned a value of 0 if it appears first in the file and "EUR" will be assigned a value of 1 if it appears second, etc. But what if you want the same ordering across a bunch of bp files? Wouldn't it be great if there was a way to just specify the integers for each pop label? This is that solution.

feat: allow for specifying the order of population labels in `Breakpoints.encode()`

---

.devcontainer.json
.github/workflows/release.yml
.github/workflows/tests.yml
.readthedocs.yaml
dev-env.yml
noxfile.py

We are officially deprecating support for py 3.8, since it is [end-of-life](https://devguide.python.org/versions/). We will support py 3.8 _unofficially_ by continuing to test our code against it in our CI, and users will still be able to install new versions of haptools with python 3.8
However, we can no longer make guarantees that future PRs will not unexpectedly drop support for py 3.8 one day, since we will be developing haptools with py 3.9 from now on. All tools that depend upon haptools should upgrade their minimum python version to 3.9

build: drop support for py 3.8 and lock at py 3.9 for development

---

.github/workflows/tests.yml
haptools/sim_genotype.py
noxfile.py

resolves https://github.com/CAST-genomics/haptools/issues/267#issuecomment-2631115628
Until now, we only use chunking to write PGEN files from `simgenotype` -- not to load from them. This PR uses the same chunk size for both. I could also add a new parameter if we want the loading to use a different chunk size than the writing.

feat: use chunking when reading from PGENs in `simgenotype`
