CAST-genomics/haptools

- haptools/sim_genotype.py
- tests/data/outvcf_out.vcf
- tests/test_outputvcf.py
New Format Field SAMPLE which has structure <Sample_name>-<Hap_variant>
Where sample name is the sample name where the variant was taken from in the vcf and hap_variant is the particular allele it contributes.
> Added SAMPLE Format Field

- haptools/__main__.py
- haptools/karyogram.py
- haptools/sim_genotype.py
If karyogram is given a centromere file it will update the last item in the haplotype blocks to become the last coordinate in the chromosome for a cleaner figure.
> Updated Karyogram

- haptools/data/haplotypes.py
- tests/test_data.py
> fix: allow extra 'extra' fields (#66)

- haptools/__main__.py
- haptools/sim_genotype.py
- haptools/transform.py
- tests/test_outputvcf.py
Added region functionality with input "chr:start-end" to only output variants and breakpoints in this region.
ex "1:1-10000"
> Added region to output_vcf

- haptools/__main__.py
- haptools/karyogram.py
- haptools/sim_genotype.py
- tests/test_outputvcf.py
Updated parsing of region to be handled in main.
Updated region to be a dictionary containing all info in 'chr' 'start' and 'end'.
Updated karyogram so it doesn't fail when centromeres file isn't present.
> Allowed either region or chroms to be specified

- docs/commands/transform.rst
- haptools/__main__.py
- haptools/data/__init__.py
- haptools/data/breakpoints.py
- haptools/data/phenotypes.py
- haptools/sim_genotype.py
- haptools/transform.py
- tests/test_data.py
> feat: use bp file in `transform`

- README.md
- docs/api/data.rst
- docs/formats/genotypes.rst
- docs/formats/haplotypes.rst
- docs/formats/phenotypes.rst
- haptools/data/genotypes.py
- pyproject.toml
and rename all mentions of `gymrek-lab`
> move our repo over to the cast org

- haptools/data/genotypes.py
- haptools/data/phenotypes.py
- haptools/sim_phenotype.py
- tests/test_data.py
- tests/test_simphenotype.py
> fix: NaNs output by simphenotype

- README.md
- docs/index.rst
- haptools/sim_genotype.py
- pyproject.toml
resolves #113
Hopefully this solves the installation issues you were having, @s041629
> dep: loosen pysam requirement

- haptools/karyogram.py
Removed brewer2mpl as a dependency and replaced with matplotlib's built in colormaps.
> Removed brewer2mpl

- docs/commands/index.rst
- docs/commands/ld.rst
- docs/commands/simphenotype.rst
- docs/commands/transform.rst
- docs/conf.py
- docs/formats/breakpoints.rst
- docs/formats/sample_info.rst
- docs/index.rst
- docs/project_info/installation.rst
- poetry.lock
- pyproject.toml
and updates to our installation instructions
> feat: new github actions

- .github/workflows/constraints.txt
- .github/workflows/tests.yml
- haptools/sim_phenotype.py
create a github action to run our test suite with `nox`
> feat: github actions for testing

- .github/workflows/tests.yml
- haptools/sim_genotype.py
- tests/test_outputvcf.py
resolves #148
Updated VCF output to output as a .gz file
> feat: updated `.vcf.gz` output in simgenotype

- docs/commands/ld.rst
- docs/commands/simphenotype.rst
- haptools/sim_genotype.py
- tests/test_index.py
- tests/test_karyogram.py
- tests/test_ld.py
- tests/test_simgenotype.py
- tests/test_simphenotype.py
- tests/test_transform.py
Finish adding automated tests for all examples in the documentation!
> test: all examples in the docs

- docs/api/data.rst
- haptools/__main__.py
- haptools/sim_phenotype.py
- tests/test_simphenotype.py
so that we can be reproducible across executions
by special request from @TaraMirmira !
> feat: add `--seed` to `simphenotype`

- docs/formats/maps.rst
Updated beagle map files link with https instead of http so it should now work.
> fix: Update maps.rst

- docs/project_info/contributing.rst
This PR is just an attempt at triggering our CD pipeline to initiate a new release. Please ignore.
> docs: add dependency to conda env build

- .github/workflows/comment_bot.yml
take 2 from #179 
or is it 3? I've lost track at this point lol
> fix: comment bot in CD pipeline

- .github/workflows/comment_bot.yml
> fix: checkout in comment bot workflow for CD pipeline

- .github/workflows/comment_bot.yml
take 4 in #181 
I'm definitely getting closer
> fix: checkout ref in comment bot from CD pipeline

- .github/workflows/comment_bot.yml
> fix: indentation in checkout build

- .github/workflows/comment_bot.yml
> fix: comment bot in build pipeline

- .github/workflows/comment_bot.yml
> fix: build workflow for comment bot

- docs/commands/simgenotype.rst
- docs/project_info/installation.rst
I removed this comment b/c I didn't think it was an issue anymore. Turns out that it still might be.
> docs: warn about pysam pip issue

- haptools/sim_genotype.py
Updated old logic within simgenotype that was incorrectly grabbing all files containing a string and not being strict with additional numbers.
> fix: Fixed faulty coord file parsing logic

- haptools/data/phenotypes.py
- tests/test_data.py
Create additional tests to verify that phenotypes are written properly.
> test: phenotype writing

- haptools/data/genotypes.py
- haptools/transform.py
- tests/test_data.py
...for merging different Genotypes instances together
resolves #82
> feat: a `Genotypes.merge_variants` method

- tests/test_ld.py
- tests/test_logging.py
> test: increase coverage of logging module

- docs/api/data.rst
- docs/formats/genotypes.rst
- docs/project_info/contributing.rst
- docs/project_info/installation.rst
- haptools/data/genotypes.py
- poetry.lock
- pyproject.toml
- tests/test_data.py
- tests/test_outputvcf.py
- tests/test_simgenotype.py
- tests/test_simphenotype.py
- tests/test_transform.py
now that wheels have been published on PyPI and the package been published to bioconda
> build: convert pgenlib from an optional to mandatory dependency

- .github/workflows/release.yml
I removed the constraints.txt in #207 but forgot to remove it in the automated releases GitHub action.
> build: try to fix broken releases action

- .github/workflows/tests.yml
- noxfile.py
Add formal support for python 3.12 in our CI
> ci: support for python 3.12

- dev-env.yml
and force a retrigger of the release system
> ci: make sure release.yml is synced with dev-env.yml

- .github/workflows/tests.yml
- noxfile.py
Add formal support for python 3.13 in our CI
> ci: add support for python 3.13
